<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder {
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run() {

		$product = [
			[
				'department_id' => 1,
				'category_id' => 1,
				'sub_category_id' => 1,
				'name' => "3 Pack Mangoes",
				'sku' => '3-pack-mangoes',
				'price' => 75,
				'commission' => 5,
				'discount' => 10,
				'total' => 240,
				'sold' => 18,
				'display' => true,
				'short_description' => "3 sweet apple mangoes going for 25/= each",
				'description' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'department_id' => 1,
				'category_id' => 1,
				'sub_category_id' => 1,
				'name' => "6 Pack Apples",
				'sku' => '3-pack-apples',
				'price' => 235,
				'commission' => 5,
				'discount' => 20,
				'total' => 400,
				'sold' => 55,
				'display' => true,
				'short_description' => "6 pack apples that are very big and super sweet, get it now!",
				'description' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'department_id' => 1,
				'category_id' => 1,
				'sub_category_id' => 1,
				'name' => "Grapes Bunch",
				'sku' => 'grape-bunch',
				'price' => 300,
				'commission' => 5,
				'discount' => 15,
				'total' => 400,
				'sold' => 55,
				'display' => true,
				'short_description' => "Organic grapes that will make your nutritionist smile.",
				'description' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'department_id' => 1,
				'category_id' => 1,
				'sub_category_id' => 1,
				'name' => "Sweet Oranges",
				'sku' => 'sweet-oranges',
				'price' => 25,
				'commission' => 5,
				'discount' => 40,
				'total' => 400,
				'sold' => 55,
				'display' => true,
				'short_description' => "Organic sweet oranges.",
				'description' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'department_id' => 2,
				'category_id' => 4,
				'sub_category_id' => 4,
				'name' => "Samsung Galaxy A13, 6.6\", 128GB + 4GB RAM (Dual SIM), 5000mAh, Black",
				'sku' => 'samsung-galaxy-a13',
				'price' => 21699,
				'commission' => 5,
				'discount' => 21,
				'total' => 120,
				'sold' => 50,
				'display' => true,
				'short_description' => "Samsung Galaxy A13 combines streamlined design aesthetics with classic colors. Refined curves make it comfortable to hold and provides easy screen navigation. Expand your view to the 6.6-inch Infinity-V Display of Galaxy A13 and see what you've been missing. Thanks to HD+ technology, your everyday content looks sharp, crisp and clear.  Similar to human eye sight, the 50MP Ultra Wide Camera sees the world with a 123-degree angle of view, adding more perspective to everything you shoot. Comes with 4GB RAM, 128GB ROM, Android 12.0 OS and is powered by a Powerful 2.0 GHz Octa-Core Processor. Order for this Samsung Galaxy A13 online from Jumia Kenya and have it delivered to your doorstep at an amazing price​",
				'description' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'department_id' => 2,
				'category_id' => 4,
				'sub_category_id' => 4,
				'name' => "Infinix Hot 12i, 6.6\", 64GB + 4GB RAM (Dual SIM), 5000mAh, 4G, Champagne Gold",
				'sku' => 'infinix-hot-12i',
				'price' => 13499,
				'commission' => 5,
				'discount' => 13,
				'total' => 120,
				'sold' => 50,
				'display' => true,
				'short_description' => "Infinix Hot 12i, 6.6\", 64GB + 4GB RAM (Dual SIM), 5000mAh, 4G, Champagne Gold​",
				'description' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'department_id' => 2,
				'category_id' => 4,
				'sub_category_id' => 4,
				'name' => "XIAOMI Redmi Note 11s, 6.43''-6GB/128GB-108MP-(Dual SIM)-5000mAh-Grey+SWiGIFTSS 64",
				'sku' => 'xiaomi-redmi-note-11s',
				'price' => 30299,
				'commission' => 5,
				'discount' => 13,
				'total' => 120,
				'sold' => 50,
				'display' => true,
				'short_description' => "The phone comes with a 6.43-inch touchscreen display with a resolution of 1080x2400 pixels. Redmi Note 11S is powered by an octa-core MediaTek Helio G96 processor. It comes with 6GB of RAM. The Redmi Note 11S runs Android 11 and is powered by a 5000mAh battery. The Redmi Note 11S supports proprietary fast charging.
As far as the cameras are concerned, the Redmi Note 11S on the rear packs a 108-megapixel primary camera with an f/1.9 aperture; an 8-megapixel camera with an f/2.2 aperture; a 2-megapixel camera with an f/2.4 aperture, and a 2-megapixel camera with an f/2.4 aperture. The rear camera setup has autofocus. It sports a 16-megapixel camera on the front for selfies with an f/2.5 aperture.
The Redmi Note 11S runs MIUI 13 is based on Android 11 and packs 128GB of inbuilt storage that can be expanded via microSD card (up to 512GB) with a dedicated slot. The Redmi Note 11S is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and Nano-SIM cards.
Connectivity options on the Redmi Note 11S include Wi-Fi, GPS, Bluetooth v5.0, NFC, Infrared, USB Type-C, 3G, and 4G (with support for Band 40 used by some LTE networks in India). Sensors on the phone include fingerprint sensor
image​",
				'description' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'department_id' => 3,
				'category_id' => 7,
				'sub_category_id' => 6,
				'name' => "Mosara Rich Conditioner - 250ml",
				'sku' => 'mosara-rich-conditioner',
				'price' => 450,
				'commission' => 5,
				'discount' => 10,
				'total' => 120,
				'sold' => 50,
				'display' => true,
				'short_description' => "Mosara's Rich Conditioner is a 3 in 1 formula that can be used as a pre-shampoo treatment, an after shampoo conditioner and as aco-wash. Place your order for this amazing product from Jumia Kenya and have it delivered to your doorstep at an amazing price

Pre-shampoo treatment: Had your hair up in a protective style and need to moisturize and bring it back to life? Apply the rich conditioner to dry hair. Detangle and cover your hair under a shower cap for 10 to 15 minutes. Rinse off and shampoo your hair as usual. 
 Co-wash: You hair feels dirty but you don't have the time for a complete wash routine? Wet your hair thoroghly. Apply a geneourous amount of the rich conditoner into your hair and massage it in. Rinse off and repeat if needed.
Condition: Just shampooed your hair and need a quick fix to balance your hair's PH and condition your hair? Apply the rich conditioner to freshly shampooed hair. Detangle your hair thorougly and rinse off. Style as usual",
				'description' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'department_id' => 3,
				'category_id' => 7,
				'sub_category_id' => 6,
				'name' => "The DD Naturals Hydrating Leave-In Conditioner - 300g",
				'sku' => 'the-dd-naturals-hydrating',
				'price' => 550,
				'commission' => 5,
				'discount' => 15,
				'total' => 120,
				'sold' => 50,
				'display' => true,
				'short_description' => "The DD Naturals Hydrating Leave-In Conditioner is made with love to promote hair growth, protect your hair from breakage and soothes your scalp.

Instantly shines, hydrates and conditions deprived hair, revealing stronger, healthier hair with a natural shine.",
				'description' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'department_id' => 3,
				'category_id' => 7,
				'sub_category_id' => 6,
				'name' => "Cantu Shea Butter Leave-In Conditioning Repair Cream - 453 G",
				'sku' => 'cantu-shea-butter-453-g',
				'price' => 875,
				'commission' => 5,
				'discount' => 27,
				'total' => 120,
				'sold' => 50,
				'display' => true,
				'short_description' => "Shea butter products are all about health and beauty to give you vibrant skin and repair damaged hair for a fresh look.
One beauty has a range of products for both men and women.Our products are of classic designs  and are affordable and perfect for your skin. We provide a variety of products including lotions, cleansers and even fragrances! We use only the highest quality ingredients and guarantee you will enjoy our full line of beauty products for looks that last all day and night!Cantu products are uniquely designed to cater for all ages irrespective of gender. one beauty the store for beauty product",
				'description' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'department_id' => 4,
				'category_id' => 13,
				'sub_category_id' => 8,
				'name' => "Fashion Infant Baby Boys Girls Clothes Sets-cat",
				'sku' => Str::slug("Fashion Infant Baby Boys Girls Clothes Sets-cat"),
				'price' => 690,
				'commission' => 5,
				'discount' => 42,
				'total' => 120,
				'sold' => 50,
				'display' => true,
				'short_description' => "1. The real color of the item may be slightly different from the pictures shown on website caused by many factors such as brightness of your monitor and light brightness.

2. Please allow slight (±2cm)manual measurement deviation for the data.

Please forgive we can't keep a 24 hours online service because of time lag, if you have any questions, order inquiry, product size, color, shipment tracking etc. please give us a message, we will reply in 24h.  If you have quality problem of the goods, please contact us asap. We will try our best to solve your problem. Please don't leave any negative feedback before you gave us this opportunity. We will provide positive feedback for the buyer as soon as the buyers pay for the products. If you are satisfied with the product and service, please give us positive feedback. We care about our valued customers, and will always try to help you. We always do our best for 100% customer satisfaction. Thanks in advance for your kindly Feedback. Hope you have a happy shopping!",
				'description' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'department_id' => 4,
				'category_id' => 13,
				'sub_category_id' => 8,
				'name' => "Dove Baby Dermacare Moisturizing Wash",
				'sku' => Str::slug("Dove Baby Dermacare Moisturizing Wash"),
				'price' => 899,
				'commission' => 5,
				'discount' => 25,
				'total' => 120,
				'sold' => 50,
				'display' => true,
				'short_description' => "Perfect for: Eczema-prone skin Caring for your baby’s eczema doesn’t have to be complicated. This Baby Dove sensitive baby wash is enriched with soothing colloidal oatmeal to ensure that it is extra gentle on eczema prone skin. Discover the benefits of colloidal oatmeal for your baby’s sensitive skin with this sensitive baby wash. • Trusted endorsements Our Derma Care Soothing Baby Wash was developed with pediatric dermatologists and approved by the National Eczema Association for your little one’s dry, irritated skin. In fact, 9 in 10 parents of babies with eczema would recommend this tear-free baby wash to other moms and dads. • Ultra-gentle baby eczema care As mild as water, this unique baby body wash formula was developed without fragrance and other potential skin irritants like sulfates, parabens, phthalates and dyes. The silky smooth formula has been tested by dermatologists. • Retaining baby skin’s moisture With prebiotic moisturizers and 100% skin-natural nutrients, this ultra-gentle cleanser helps retain moisture in your baby’s skin to prevent dryness. So you can enjoy your little one’s skin feeling baby s",
				'description' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'department_id' => 4,
				'category_id' => 13,
				'sub_category_id' => 8,
				'name' => "Dove Baby Dermacare Moisturizing Wash",
				'sku' => Str::slug("Dove Baby Dermacare Moisturizing Wash"),
				'price' => 899,
				'commission' => 5,
				'discount' => 25,
				'total' => 120,
				'sold' => 50,
				'display' => true,
				'short_description' => "Perfect for: Eczema-prone skin Caring for your baby’s eczema doesn’t have to be complicated. This Baby Dove sensitive baby wash is enriched with soothing colloidal oatmeal to ensure that it is extra gentle on eczema prone skin. Discover the benefits of colloidal oatmeal for your baby’s sensitive skin with this sensitive baby wash. • Trusted endorsements Our Derma Care Soothing Baby Wash was developed with pediatric dermatologists and approved by the National Eczema Association for your little one’s dry, irritated skin. In fact, 9 in 10 parents of babies with eczema would recommend this tear-free baby wash to other moms and dads. • Ultra-gentle baby eczema care As mild as water, this unique baby body wash formula was developed without fragrance and other potential skin irritants like sulfates, parabens, phthalates and dyes. The silky smooth formula has been tested by dermatologists. • Retaining baby skin’s moisture With prebiotic moisturizers and 100% skin-natural nutrients, this ultra-gentle cleanser helps retain moisture in your baby’s skin to prevent dryness. So you can enjoy your little one’s skin feeling baby s",
				'description' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'department_id' => 4,
				'category_id' => 13,
				'sub_category_id' => 8,
				'name' => "Cussons Baby Middle, Gentle And Unperfumed Jelly~200 ML",
				'sku' => Str::slug("Cussons Baby Middle, Gentle And Unperfumed Jelly~200 ML"),
				'price' => 650,
				'commission' => 5,
				'discount' => 25,
				'total' => 120,
				'sold' => 50,
				'display' => true,
				'short_description' => "The Cussons Baby M&G Unperf Jelly 200 ML is frendly to your child enhancing their skin care and keeps them protected from germs. we offer you an extra soap gift for shopping with us to ensure you take more care of the gift from God~ your child.order for this excellent product from the trusted brands CUSSON BABY from Jumia and have it at your doorstep.",
				'description' => null,
				'created_at' => now(),
				'updated_at' => now(),
			],
		];
		DB::table('products')->insert($product);


		$productImages = [
			[
				'product_id' => 1,
				'image' => 'images/products/mangoes.jpg',
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'product_id' => 2,
				'image' => 'images/products/6-pack.jpg',
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'product_id' => 3,
				'image' => 'images/products/grapes.jpg',
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'product_id' => 4,
				'image' => 'images/products/oranges.jpg',
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'product_id' => 5,
				'image' => 'images/products/samsung.jpg',
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'product_id' => 6,
				'image' => 'images/products/infinix.jpg',
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'product_id' => 7,
				'image' => 'images/products/xiaomi.jpg',
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'product_id' => 8,
				'image' => 'images/products/mosala.jpg',
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'product_id' => 9,
				'image' => 'images/products/dd-naturals.jpg',
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'product_id' => 10,
				'image' => 'images/products/cantu.jpg',
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'product_id' => 11,
				'image' => 'images/products/baby_clothe.jpg',
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'product_id' => 12,
				'image' => 'images/products/baby_dove.jpg',
				'created_at' => now(),
				'updated_at' => now(),
			],
			[
				'product_id' => 13,
				'image' => 'images/products/cussions.jpg',
				'created_at' => now(),
				'updated_at' => now(),

			],
		];
		DB::table('product_images')->insert($productImages);
	}
}
